/* 🤖 this file was generated by svg-to-ts*/
export const svgIconHome: {
  name: 'home';
  data: string;
} = {
  name: 'home',
  data: `<svg width="25" height="25" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20.313 25h-4.167a.521.521 0 01-.521-.52v-7.292a.521.521 0 00-.52-.52h-5.21a.521.521 0 00-.52.52v7.292c0 .287-.233.52-.52.52H4.686a1.564 1.564 0 01-1.562-1.562v-9.896H1.042a1.043 1.043 0 01-.734-1.784L12.135.149a.522.522 0 01.73 0l11.822 11.605a1.043 1.043 0 01-.73 1.788h-2.082v9.896c0 .861-.701 1.562-1.563 1.562zm-3.646-1.041h3.645c.288 0 .521-.234.521-.521V13.02c0-.287.234-.52.521-.52h2.604L12.5 1.25 1.042 12.498l2.604.004c.287 0 .52.233.52.52v10.417c0 .287.234.52.521.52h3.646v-6.77c0-.861.701-1.563 1.563-1.563h5.208c.862 0 1.563.701 1.563 1.563v6.77z" fill="#F9F9F9" stroke="#F6FBF5" stroke-width="2"/></svg>`
};
export const svgIconMore: {
  name: 'more';
  data: string;
} = {
  name: 'more',
  data: `<svg width="25" height="25" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0)"><path d="M3.571 8.928a3.571 3.571 0 100 7.143 3.571 3.571 0 000-7.143zm0 5.358a1.786 1.786 0 110-3.572 1.786 1.786 0 010 3.572zM12.5 8.928a3.571 3.571 0 100 7.143 3.571 3.571 0 000-7.143zm0 5.358a1.786 1.786 0 110-3.572 1.786 1.786 0 010 3.572z" fill="#fff"/><path d="M21.429 8.928a3.571 3.571 0 100 7.143 3.571 3.571 0 000-7.143zm0 5.358a1.786 1.786 0 110-3.572 1.786 1.786 0 010 3.572z" fill="#F9F9F9"/></g><defs><clipPath id="clip0"><path fill="#fff" d="M0 0h25v25H0z"/></clipPath></defs></svg>`
};
export type svgIcon = 'home' | 'more';
export interface SvgIcon {
  name: svgIcon;
  data: string;
}
export type SvgIconNameSubset<
  T extends Readonly<SvgIcon[]>
> = T[number]['name'];
